In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("data/messy_HR_data.csv")
df

,Name,Age,Salary,Gender,Department,Position,Joining Date,Performance Score,Email,Phone Number
0,grace,25,50000,Male,HR,Manager,"April 5, 2018",D,email@example.com,NaN
1,david,NaN,65000,Female,Finance,Director,2020/02/20,F,user@domain.com,123-456-7890
2,hannah,35,SIXTY THOUSAND,Female,Sales,Director,01/15/2020,C,email@example.com,098-765-4321
3,eve,NaN,50000,Female,IT,Manager,"April 5, 2018",A,name@company.org,
4,grace,NaN,NAN,Female,Finance,Manager,01/15/2020,F,name@company.org,098-765-4321
...,...,...,...,...,...,...,...,...,...,...
995,jack,50,65000,Female,HR,Manager,2020/02/20,F,NaN,098-765-4321
996,jack,thirty,50000,Male,Finance,Analyst,"April 5, 2018",C,NaN,555-555-5555
997,hannah,thirty,70000,Male,IT,Assistant,01/15/2020,D,user@domain.com,NaN
998,bob,25,65000,Other,Marketing,Manager,"April 5, 2018",D,email@example.com,NaN
999,ivy,thirty,SIXTY THOUSAND,Male,Finance,Manager,2020/02/20,C,user@domain.com,123-456-7890

In [3]:
df.reset_index(inplace=True)

In [4]:
rows ,colums = df.shape #/It is a tuple

In [5]:
df.head()

,index,Name,Age,Salary,Gender,Department,Position,Joining Date,Performance Score,Email,Phone Number
0,0,grace,25,50000,Male,HR,Manager,"April 5, 2018",D,email@example.com,NaN
1,1,david,NaN,65000,Female,Finance,Director,2020/02/20,F,user@domain.com,123-456-7890
2,2,hannah,35,SIXTY THOUSAND,Female,Sales,Director,01/15/2020,C,email@example.com,098-765-4321
3,3,eve,NaN,50000,Female,IT,Manager,"April 5, 2018",A,name@company.org,
4,4,grace,NaN,NAN,Female,Finance,Manager,01/15/2020,F,name@company.org,098-765-4321

In [6]:
df.head()

,index,Name,Age,Salary,Gender,Department,Position,Joining Date,Performance Score,Email,Phone Number
0,0,grace,25,50000,Male,HR,Manager,"April 5, 2018",D,email@example.com,NaN
1,1,david,NaN,65000,Female,Finance,Director,2020/02/20,F,user@domain.com,123-456-7890
2,2,hannah,35,SIXTY THOUSAND,Female,Sales,Director,01/15/2020,C,email@example.com,098-765-4321
3,3,eve,NaN,50000,Female,IT,Manager,"April 5, 2018",A,name@company.org,
4,4,grace,NaN,NAN,Female,Finance,Manager,01/15/2020,F,name@company.org,098-765-4321

In [7]:
df.Salary[:]

0               50000
1               65000
2      SIXTY THOUSAND
3               50000
4                NAN
            ...
995             65000
996             50000
997             70000
998             65000
999    SIXTY THOUSAND
Name: Salary, Length: 1000, dtype: str

In [8]:
df['Salary'] = df['Salary'].replace('SIXTY THOUSAND',60000)

In [9]:
print(df['Salary'].unique())

['50000' '65000' 60000 ' NAN ' '70000' '55000']

In [10]:
df['Salary'] = df['Salary'].replace(' NAN ',0)

In [11]:
df['Salary'] = pd.to_numeric(df['Salary'])

In [12]:
print(df['Salary'].unique())

[50000 65000 60000     0 70000 55000]

In [13]:
df.Salary

0      50000
1      65000
2      60000
3      50000
4          0
       ...
995    65000
996    50000
997    70000
998    65000
999    60000
Name: Salary, Length: 1000, dtype: int64

In [14]:
df.Salary.mean()

np.float64(50160.0)

In [38]:
df.Salary.unique()

array([50000, 65000, 60000,     0, 70000, 55000])

In [39]:
df['Salary']=df['Salary'].replace(0,50140)

In [15]:
df.Age.unique()

<StringArray>
['25', nan, '35', '40', 'thirty', '50']
Length: 6, dtype: str

In [16]:
df['Age'] = df.Age.replace('thirty',30)

In [17]:
df['Age'] = pd.to_numeric(df['Age'])

In [18]:
df.Age.mean()

np.float64(35.8026159334126)

In [26]:
df.Age.unique()

array([25., nan, 35., 40., 30., 50.])

In [31]:
df['Age'] = df['Age'].fillna(35)
df.Age

0      25.0
1      35.0
2      35.0
3      35.0
4      35.0
       ...
995    50.0
996    30.0
997    30.0
998    25.0
999    30.0
Name: Age, Length: 1000, dtype: float64

In [41]:
df.Email.unique()

<StringArray>
['email@example.com', 'user@domain.com', 'name@company.org', nan]
Length: 4, dtype: str

In [43]:
df['Email'] = df['Email'].fillna('user@domain,com')

In [45]:
df['Phone Number'].unique()

<StringArray>
[nan, '123-456-7890', '098-765-4321', ' ', '555-555-5555']
Length: 5, dtype: str

In [46]:
df['Phone Number'] = df['Phone Number'].fillna(123-456-7777)

In [47]:
df['Phone Number'] = df['Phone Number'].fillna(101-111-2345)

In [48]:
df

,index,Name,Age,Salary,Gender,Department,Position,Joining Date,Performance Score,Email,Phone Number
0,0,grace,25.0,50000,Male,HR,Manager,"April 5, 2018",D,email@example.com,-8110
1,1,david,35.0,65000,Female,Finance,Director,2020/02/20,F,user@domain.com,123-456-7890
2,2,hannah,35.0,60000,Female,Sales,Director,01/15/2020,C,email@example.com,098-765-4321
3,3,eve,35.0,50000,Female,IT,Manager,"April 5, 2018",A,name@company.org,
4,4,grace,35.0,50140,Female,Finance,Manager,01/15/2020,F,name@company.org,098-765-4321
...,...,...,...,...,...,...,...,...,...,...,...
995,995,jack,50.0,65000,Female,HR,Manager,2020/02/20,F,"user@domain,com",098-765-4321
996,996,jack,30.0,50000,Male,Finance,Analyst,"April 5, 2018",C,"user@domain,com",555-555-5555
997,997,hannah,30.0,70000,Male,IT,Assistant,01/15/2020,D,user@domain.com,-8110
998,998,bob,25.0,65000,Other,Marketing,Manager,"April 5, 2018",D,email@example.com,-8110
999,999,ivy,30.0,60000,Male,Finance,Manager,2020/02/20,C,user@domain.com,123-456-7890

In [49]:
df.to_csv('cleaned_data.csv', index=False)

In [50]:
import os
print(os.getcwd())

C:\Users\swast\PycharmProjects\JupyterProjectforPandas,numpyetc