In [ ]:
import pandas as pd

In [4]:
df = pd.read_csv('messy_HR_data.csv')
df

,Name,Age,Salary,Gender,Department,Position,Joining Date,Performance Score,Email,Phone Number
0,grace,25,50000,Male,HR,Manager,"April 5, 2018",D,email@example.com,NaN
1,david,NaN,65000,Female,Finance,Director,2020/02/20,F,user@domain.com,123-456-7890
2,hannah,35,SIXTY THOUSAND,Female,Sales,Director,01/15/2020,C,email@example.com,098-765-4321
3,eve,NaN,50000,Female,IT,Manager,"April 5, 2018",A,name@company.org,
4,grace,NaN,NAN,Female,Finance,Manager,01/15/2020,F,name@company.org,098-765-4321
...,...,...,...,...,...,...,...,...,...,...
995,jack,50,65000,Female,HR,Manager,2020/02/20,F,NaN,098-765-4321
996,jack,thirty,50000,Male,Finance,Analyst,"April 5, 2018",C,NaN,555-555-5555
997,hannah,thirty,70000,Male,IT,Assistant,01/15/2020,D,user@domain.com,NaN
998,bob,25,65000,Other,Marketing,Manager,"April 5, 2018",D,email@example.com,NaN
999,ivy,thirty,SIXTY THOUSAND,Male,Finance,Manager,2020/02/20,C,user@domain.com,123-456-7890

In [7]:
cf = pd.read_csv("cleaned_data.csv")

In [8]:
cf

,index,Name,Age,Salary,Gender,Department,Position,Joining Date,Performance Score,Email,Phone Number
0,0,grace,25.0,50000,Male,HR,Manager,"April 5, 2018",D,email@example.com,-8110
1,1,david,35.0,65000,Female,Finance,Director,2020/02/20,F,user@domain.com,123-456-7890
2,2,hannah,35.0,60000,Female,Sales,Director,01/15/2020,C,email@example.com,098-765-4321
3,3,eve,35.0,50000,Female,IT,Manager,"April 5, 2018",A,name@company.org,
4,4,grace,35.0,50140,Female,Finance,Manager,01/15/2020,F,name@company.org,098-765-4321
...,...,...,...,...,...,...,...,...,...,...,...
995,995,jack,50.0,65000,Female,HR,Manager,2020/02/20,F,"user@domain,com",098-765-4321
996,996,jack,30.0,50000,Male,Finance,Analyst,"April 5, 2018",C,"user@domain,com",555-555-5555
997,997,hannah,30.0,70000,Male,IT,Assistant,01/15/2020,D,user@domain.com,-8110
998,998,bob,25.0,65000,Other,Marketing,Manager,"April 5, 2018",D,email@example.com,-8110
999,999,ivy,30.0,60000,Male,Finance,Manager,2020/02/20,C,user@domain.com,123-456-7890